### ISSUE TITLE
check mobile view of www_mastodon

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_mastodon#8]
- [x] fix mobile view margin, top header no margin, text a bit too big 

<img width="380" alt="Screenshot 2023-05-22 at 15 50 51" src="https://github.com/threefoldfoundation/www_mastodon/assets/43240801/a8f20687-3665-485c-b9d6-3d277685679c">
<img width="465" alt="Screenshot 2023-05-22 at 15 50 42" src="https://github.com/threefoldfoundation/www_mastodon/assets/43240801/ba96595a-d452-46b5-9baa-91999da8a485">

- [x] make sure has staging and master like other website

- [x] update eadme

**Comment by ehab-hassan** [comment]
done

**Comment by sasha-astiadi** [comment]
thank you @ehab-hassan
